#%RAML 1.0
title: RAML for Scheme Adapter
version: v1
baseUri: https://localhost:8088/scheme/adapter/{version}

types:

  QuoteRequest:
    type: object
    properties:
      paymentId: string
      payer: Person
      payee: Person
      amountType:
        type:
          enum: [SEND, RECEIVE]
      amount: Amount
      fees?: Amount
      transferType: TransferType

  QuoteResponse:
    type: object
    properties:
      paymentId: string
      receiveAmount: Amount
      payeeFee: Amount
      payeeCommission: Amount
      ipr?: string

  PaymentRequest:
    type: object
    properties:
      ipr: string
      sourceAmount:
        type: number
        format: float
      sourceAccount: string
      connectorAccount: string
      sourceExpiryDuration: integer

  PaymentResponse:
    type: object
    properties:
      paymentId: string
      connectorAccount: string
      status:
        type:
          enum: [executed, rejected, expired]
      rejectionMessage: string
      fulfillment: string

  Person:
    type: object
    properties:
      identifier: string
      identifierType: string
      url?: string
      account?: string
      
  Amount: 
    type: object
    properties:
      amount: number
      currency: string
  
  TransferType:
    type: object
    properties:
      scenario: string
      initiator?:
        type:
          enum: [PAYER, PAYEE, PROXY]
  
  HealthStatus:
    type: object
    properties: 
      status:
        type: string
        required: true
       
  ILPAddress:
    type: object
    properties: 
      ilpAddress:
        type: string
        required: true
        
  NotificationRequest:
      type: object
      properties:
        ipr: string
        paymentId: string
        destinationAccount: string
        status:
          type:
            enum: [prepared, executed]
        fulfillment?: string

/quotes:
  displayName: /v1/quotes/
  post:
      description: Submit a request for a quote.
      body:
        application/json:
         type: QuoteRequest
         
      responses:
        201:
          body:
            application/json:
             type: QuoteResponse
             #example: !include payments-response-sample.json
               
/health:
  displayName: HealthCheck resource
  description: This resource is included to provide a simple response to indicate that the API is up and running.
  get:
    responses: 
      200:
        body: 
          application/json: 
            type: HealthStatus
            example: |
              { 
                "status" : "ok" 
              }

/ilpAddress:
  displayName: ILP Address
  description: This resource indicates ILP payment request packet
  get:
    queryParameters:
          account: string
    responses: 
      200:
        body: 
          application/json: 
            type: ILPAddress
            example: |
              { 
                "ilpAddress" : "ok" 
              }

/payments:
  displayName: Payments
  description: Endpoint to submit the payments
  post:
      body:
        application/json:
         type: PaymentRequest
         #example: !include invoice-request-sample.json
      responses:
        201:
          description: "ok"
          body:
              application/json:
               type: PaymentResponse
               
/notifications:
  displayName: Notifications
  description: ILP Service calls this endpoint to validate the prepare before proceesding further on fulfillment
  post:
      body:
        application/json:
         type: NotificationRequest
      responses:
        200:
          description: "Success"