#%RAML 1.0
title: RAML for Scheme Adapter
version: v1
baseUri: https://localhost:8088/scheme/adapter/{version}

types:

  QuoteRequest:
    type: object
    properties:
      quoteId: string
      transferId?: string
      payer: Person
      payee: Person
      amountType:
        type:
          enum: [SEND, RECEIVE]
      amount: Amount
      fees?: Amount
      transactionType: TransactionType

  QuoteResponse:
    type: object
    properties:
      quoteId: string
      transferId: string
      receiveAmount: Amount
      payeeFee: Amount
      payeeCommission: Amount
      ipr?: string

  PaymentRequest:
    type: object
    properties:
      ipr: string
      sourceAmount:
        type: number
        format: float
      sourceAccount: string
      connectorAccount: string
      sourceExpiryDuration: integer

  PaymentResponse:
    type: object
    properties:
      paymentId: string
      connectorAccount: string
      status:
        type:
          enum: [executed, rejected, expired]
      rejectionMessage: string
      fulfillment: string

  Person:
    type: object
    properties:
      identifier: string
      identifierType?: string
      submissionUrl?: string
      
  Amount: 
    type: object
    properties:
      amount: number
      currency: string
  
  TransactionType:
    type: object
    properties:
      scenario: string
      initiator:
        type:
          enum: [PAYER, PAYEE, PROXY]
  
  HealthStatus:
    type: object
    properties: 
      status:
        type: string
        required: true

/quotes:
  displayName: /v1/quotes/
  post:
      description: Submit a request for a quote.
      body:
        application/json:
         type: QuoteRequest
         
      responses:
        201:
          body:
            application/json:
             type: QuoteResponse
             #example: !include payments-response-sample.json
               
/health:
  displayName: HealthCheck resource
  description: This resource is included to provide a simple response to indicate that the API is up and running.
  get:
    responses: 
      200:
        body: 
          application/json: 
            type: HealthStatus
            example: |
              { 
                "status" : "ok" 
              }

/payments:
  displayName: Payments
  description: Endpoint to submit the payments
  post:
      body:
        application/json:
         type: PaymentRequest
         #example: !include invoice-request-sample.json
      responses:
        201:
          description: "ok"
          body:
              application/json:
               type: PaymentResponse           