swagger: '2.0'
info:
  title: interop-scheme-adapter
  description: Scheme Adapter
  version: V1

#host: ec2-52-37-54-209.us-west-2.compute.amazonaws.com:8088
schemes:
  - http
  - https

basePath: /scheme/adapter/v1
consumes:
  - application/json
produces:
  - application/json


paths:
  /quotes:
    post:
      description: Request for a quote
      parameters:
        - name: Quote Request
          in: body
          description: request object
          schema:
            $ref: '#/definitions/QuoteRequest'

      responses:
        200:
          description: quote response
          schema:
            $ref: '#/definitions/QuoteResponse'

  /payments:
    post:
      summary: Submit Payment
      parameters:
        - name: Payment Request
          in: body
          schema:
            $ref: '#/definitions/PaymentRequest'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/PaymentResponse'

  /notifications:
    post:
      summary: Submit Notification
      parameters:
        - name: Notification Request
          in: body
          schema:
            $ref: '#/definitions/NotificationRequest'
      responses:
        200:
          description: Success
          

definitions:

  QuoteRequest:
    title: Quote Request
    type: object
    properties:
      paymentId:
        type: string
      payer:
        $ref: '#/definitions/Person'
      payee:
        $ref: '#/definitions/Person'
      amountType:
        $ref: '#/definitions/AmountTypeEnum'
      amount:
        $ref: '#/definitions/Amount'
      fees:
        $ref: '#/definitions/Amount'
      transferType:
        $ref: '#/definitions/TransferType'
    required:
      - paymentId
      - payer
      - payee
      - amountType
      - transferType


  QuoteResponse:
    title: Quote Response
    type: object
    properties:
      paymentId:
        type: string
      receiveAmount:
        $ref: '#/definitions/Amount'
      payeeFee:
        $ref: '#/definitions/Amount'
      payeeCommission:
        $ref: '#/definitions/Amount'
      ipr:
        type: string
      sourceExpiryDuration:
        type: number
        format: integer
    required:
      - paymentId
      - receiveAmount
      - payeeFee
      - payeeCommission

  PaymentRequest:
    title: Payment Request
    type: object
    properties:
      ipr:
        type: string
      sourceAmount:
        type: number
        format: decimal
      sourceAccount:
        type: string
      connectorAccount:
        type: string
      sourceExpiryDuration:
        type: number
        format: integer

  PaymentResponse:
    title: Payment Response
    type: object
    properties:
      paymentId:
        type: string
      connectorAccount:
        type: string
      status:
        $ref: '#/definitions/StatusEnum'
      rejectionMessage:
        type: string
      fulfillment:
        type: string

  Amount:
    title: Amount
    type: object
    properties:
      amount:
        type: number
        format: double
      currency:
        type: string

  Person:
    title: Person Object
    type: object
    properties:
      identifier:
        type: string
      identifierType:
        type: string
      url:
        type: string
      account:
        type: string
    required:
      - identifier
      - identifierType

  TransferType:
    title: Transfer Object
    type: object
    properties:
      scenario:
        type: string
      initiator:
        $ref: '#/definitions/InitiatorEnum'
    required:
      - scenario
      
  NotificationRequest:
    title: Notification Request
    type: object
    properties:
      ipr:
        type: string
      paymentId:
        type: string
      destinationAccount:
        type: string
      status:
        $ref: '#/definitions/StatusEnum'
      fulfillment:
        type: string
    required:
      - ipr
      - paymentId
      - destinationAccount
      - status

  StatusEnum:
    title: statusEnum
    type: string
    enum:
    - prepared
    - executed
    - rejected
    - expired

  AmountTypeEnum:
    title: Amount Type Enum
    type: string
    enum:
    - SEND
    - RECEIVE

  InitiatorEnum:
    title: Initiator Enum
    type: string
    enum:
    - PAYER
    - PAYEE
    - PROXY